language: java

# Before we start doing anything, install a stock LLVM
install:
    - sudo sh -c "echo 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.4 main' >> /etc/apt/sources.list"
    - sudo sh -c "echo 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise main' >> /etc/apt/sources.list"
    - sudo sh -c "echo 'deb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu precise main' >> /etc/apt/sources.list"
    - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -
    - sudo apt-get update -qq
    - sudo apt-get install -qq --force-yes -y llvm-$LLVM_VERSION llvm-${LLVM_VERSION}-dev clang-$LLVM_VERSION lldb-$LLVM_VERSION
    
# All of the llvm tools are suffixed with "-$VERS" which we don't want, so
# symlink them all into a local directory and just use that
before_script:
    - mkdir -p local-llvm/bin
    - ln -nsf /usr/bin/llvm-config-$LLVM_VERSION local-llvm/bin/llvm-config
    - ln -nsf /usr/bin/llvm-mc-$LLVM_VERSION local-llvm/bin/llvm-mc
    - ln -nsf /usr/bin/llvm-as-$LLVM_VERSION local-llvm/bin/llvm-as
    - ln -nsf /usr/bin/llvm-dis-$LLVM_VERSION local-llvm/bin/llvm-dis
    - ln -nsf /usr/bin/llc-$LLVM_VERSION local-llvm/bin/llc
    - ln -nsf /usr/include/llvm-$LLVM_VERSION local-llvm/include
    - ./configure --disable-optimize-tests --llvm-root=`pwd`/local-llvm
    --enable-fast-make --enable-clang
    
env:
    global:
        - NO_BENCH=1
    matrix:
        - LLVM_VERSION=3.3
        - LLVM_VERSION=3.4

# We track this ourselves, and in theory we don't have to update the LLVM repo
# (but sadly we do right now anyway).
git:
    submodules: false
    
branches:
    only:
    - travis-ci